### ISSUE TITLE
uploading timeseries sometimes fail.  error 500 internal error

### ISSUE THREAD

**Issue by miwamasa** [BrickSchema/brick-server#12]
Thanks for great implementation!
I have tested using docker-compose on Centos7

When I try to upload relatively long timeseries ( two month of  every minutes sensor data), the uploading by posting /data/timeseries  does sometimes fails (500 internal error).

The brick server log says:

> File "/app/brick_server/services/data.py", line 120, in post
    await asyncio.gather(futures)
  File "/usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py", line 279, in add_data
    await self._add_number_data(data)
  File "/usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py", line 237, in _add_number_data
    res = await self._bulk_upsert_data(encoded_data, 'number')
  File "/usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py", line 249, in _bulk_upsert_data
    async with self.pool.acquire() as conn:
AttributeError: 'AsyncpgTimeseries' object has no attribute 'pool'

**Comment by miwamasa** [comment]
my testing code looks like this. 
status code of post respond is sometime 200 but not always.

```
from urllib.parse import quote_plus
import pdb
import requests
from pdb import set_trace as bp

import os
from copy import deepcopy
from rdflib import Namespace

BRICK_VERSION = '1.0.3'
BRICK = Namespace(f'https://brickschema.org/schema/{BRICK_VERSION}/Brick#')

#whatever
HOSTNAME = 'http://hogehoge.com:8004'
API_BASE = HOSTNAME + '/brickapi/v1'
ENTITY_BASE = API_BASE + '/entities'
QUERY_BASE = API_BASE + '/rawqueries'
DATA_BASE = API_BASE + '/data'
ACTUATION_BASE = API_BASE + '/actuation'
AUTH_BASE = HOSTNAME + '/auth'

#you must change jwt_token
default_headers = {
    "Authorization": "Bearer " + "XXXXX"}

def authorize_headers(headers={}):
    headers.update(default_headers)
    return headers

#load ttl
with open('bldg.ttl', 'rb') as fp:
        headers = authorize_headers({
            'Content-Type': 'text/turtle',
        })
        resp = requests.post(ENTITY_BASE + '/upload', headers=headers, data=fp, allow_redirects=False)
resp

znt_id ='bldg:BLDG_RM101_ZN_T'
znt_t0 = 1581161300.51
znt_t1 = 1581161310.3
znt_data=[]
# every minutes for two month
for i in range(60*24*60):
    znt_data.append([znt_id,znt_t0+i, i*1.2 ])

def upload_timeseries(znt_data):
    print('uploading..'+znt_id)
    body = {
        'data': znt_data,
        'fields': ['uuid', 'timestamp', 'number'],
        }
    headers = authorize_headers()
    resp = requests.post(DATA_BASE + '/timeseries', json=body, headers=headers)
    if resp.status_code !=200:
        print ('   upload_error='+str(resp.status_code))
    return resp.status_code 

upload_timeseries(znt_data)
```

**Comment by miwamasa** [comment]
It ran with my docker on the window OS!  It seems that the host(CentOS) does not have enough resource to run brick-server.
Sorry for confusion. And hope that someone that may come up with the same situation, please look at error logs of the containers.

**Comment by jli113** [comment]
I have the same problem, switching computers does not help.

**Comment by jli113** [comment]
brickserver             | 172.20.0.1:49544 - "POST /brickapi/v1/data/timeseries HTTP/1.1" 500
brickserver             | [2021-07-22 10:52:45 +0000] [29] [ERROR] Exception in ASGI application
brickserver             | Traceback (most recent call last):
brickserver             |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
brickserver             |     result = await app(self.scope, self.receive, self.send)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
brickserver             |     return await self.app(scope, receive, send)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 171, in __call__
brickserver             |     await super().__call__(scope, receive, send)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
brickserver             |     await self.middleware_stack(scope, receive, send)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
brickserver             |     raise exc from None
brickserver             |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
brickserver             |     await self.app(scope, receive, _send)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/sessions.py", line 75, in __call__
brickserver             |     await self.app(scope, receive, send_wrapper)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
brickserver             |     raise exc from None
brickserver             |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
brickserver             |     await self.app(scope, receive, sender)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
brickserver             |     await route.handle(scope, receive, send)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
brickserver             |     await self.app(scope, receive, send)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
brickserver             |     response = await func(request)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 201, in app
brickserver             |     dependant=dependant, values=values, is_coroutine=is_coroutine
brickserver             |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
brickserver             |     return await dependant.call(**values)
brickserver             |   File "/app/brick_server/auth/authorization.py", line 161, in decorated
brickserver             |     return await f(*args, **kwargs)
brickserver             |   File "/app/brick_server/services/data.py", line 120, in post
brickserver             |     await asyncio.gather(futures)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py", line 279, in add_data
brickserver             |     await self._add_number_data(data)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py", line 237, in _add_number_data
brickserver             |     res = await self._bulk_upsert_data(encoded_data, 'number')
brickserver             |   File "/usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py", line 249, in _bulk_upsert_data
brickserver             |     async with self.pool.acquire() as conn:
brickserver             | AttributeError: 'AsyncpgTimeseries' object has no attribute 'pool'

**Comment by jli113** [comment]
This is definitely a problem, it just worked, for no reason.
