### ISSUE TITLE
More description for Ansible

### ISSUE THREAD

**Issue by jbkoh** [BrickSchema/brick-server#3]
@gtfierro Could you detail the instruction for Ansible a bit more? Especially what should a user fill in for "the remote host"? Is it the hostname of the server that we'd like to run the code?

**Comment by gtfierro** [comment]
[Yes](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html)

You can also set it to localhost if you want. I can submit a PR tomorrow with some clarifications

**Comment by jbkoh** [comment]
That'd be great. Thanks.
