### ISSUE TITLE
Brick server frond end in brick server docker image

### ISSUE THREAD

**Issue by s0301132** [BrickSchema/brick-server#7]
Hi @jbkoh, 

I saw the front end package in manual installation page, but I can't find any tutorial about this frond end, how can I use this frond end in docker image or where can I find the tutorial about this frond end? Thanks!

[https://gitlab.com/jbkoh/brick-server-frontend](url)

**Comment by jbkoh** [comment]
@s0301132 The frontend is still actively being developed so not ready to be shipped yet. I will update the docker-compose file once it's ready.

**Comment by s0301132** [comment]
@jbkoh OK Thanks!
